Repository vitech-team/mood-feed-frontend, pull requests merged in 2020-11, with the labels that each got.

#60 fix: changes to verify large test execution
  preview/helmfile.yaml
  src/index.html
Labels: approved, size/XS

#57 feat(SDLC-41): Create OAuth integration for project
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/auth.config.module.ts
  src/app/auth/auth.config.service.ts
  src/app/auth/auth.config.ts
  src/app/auth/auth.guard.ts
  src/app/feed/feed.component.html
  src/app/feed/feed.component.scss
  src/app/feed/feed.component.spec.ts
  src/app/feed/feed.component.ts
  src/app/feed/feed.module.ts
  src/app/login/login.component.html
  src/app/login/login.component.scss
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/app/login/login.module.ts
  src/app/rest-client/user.service.spec.ts
  src/app/rest-client/user.service.ts
  src/app/user-menu/user-menu.component.html
  src/app/user-menu/user-menu.component.scss
  src/app/user-menu/user-menu.component.spec.ts
  src/app/user-menu/user-menu.component.ts
  src/app/user-menu/user-menu.module.ts
  src/app/user/user.component.html
  src/app/user/user.component.scss
  src/app/user/user.component.spec.ts
  src/app/user/user.component.ts
  src/app/user/user.module.ts
Labels: size/XL

#76 fix: fix for local run
  package.json
  src/environments/environment.ts
Labels: approved, size/XS

#78 chore: test
  .lighthouse/Kptfile
  .lighthouse/secrets/gitleaks.toml
  .lighthouse/secrets/secrets.yaml
  .lighthouse/secrets/triggers.yaml
  charts/mood-feed-frontend/Chart.yaml
  charts/mood-feed-frontend/Kptfile
  charts/mood-feed-frontend/templates/deployment.yaml
  charts/mood-feed-frontend/templates/ingress.yaml
  charts/mood-feed-frontend/templates/ksvc.yaml
  charts/mood-feed-frontend/templates/sa.yaml
  charts/mood-feed-frontend/values.yaml
  preview/backend-values.yaml
  preview/helmfile.yaml
  preview/mysql-values.yaml
  preview/values.yaml.gotmpl
  src/app/auth/auth.config.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/L
