Repository vitech-team/mood-feed-frontend, pull requests merged in 2020-10, with the labels that each got.

#46 feat: add semantic version
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#47 fix: check semantic version fix
  .lighthouse/jenkins-x/conventionalcommits.yaml
Labels: approved, size/XS

#48 feat: check semantic version feat
  .lighthouse/jenkins-x/conventionalcommits.yaml
Labels: approved, size/XS

#52 chore: test new pipelines
  .lighthouse/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
  charts/mood-feed-frontend/Kptfile
  charts/mood-feed-frontend/templates/deployment.yaml
  jenkins-x.yml
  package-lock.json
  package.json
  preview/Kptfile
  server.js
  sonar-project.properties
Labels: size/XXL

#53 Shared pipelines
  .lighthouse/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  .lighthouse/jenkins-x/triggers.yaml
Labels: size/L

#59 chore: test pipeline
  preview/helmfile.yaml
Labels: size/XS
