Repository vitech-team/mood-feed-frontend, pull requests merged in 2020-09, with the labels that each got.

#11 Update pipeline
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  nginx.conf
  src/environments/environment.prod.ts
Labels: approved, size/M

#12 Moved npm build out of docker
  .gitignore
  Dockerfile
  jenkins-x.yml
Labels: approved, size/M

#13 try fixed image
  jenkins-x.yml
Labels: approved, lgtm, size/S

#15 Added lint check
  jenkins-x.yml
  src/app/feed/message/message.component.spec.ts
  src/app/rest-client/message.service.spec.ts
Labels: approved, size/S

#21 Convensional commits
  README.md
  jenkins-x.yml
  preview/Kptfile
  preview/helmfile.yaml
  preview/values.yaml.gotmpl
Labels: size/M

#23 fix: add environment variables
  jenkins-x.yml
Labels: size/S

#25 feat: add sonar check to pull request
  jenkins-x.yml
  package-lock.json
  sonar-project.properties
Labels: size/M

#29 fix: coverage
  jenkins-x.yml
  sonar-project.properties
Labels: size/XS

#30 fix: check coverage
  jenkins-x.yml
  src/app/rest-client/message.service.ts
Labels: size/M

#31 fix: removed test code
  src/app/rest-client/message.service.ts
Labels: size/XS

#32 fix: fixed sonar issues
  src/app/feed/feed.component.html
  src/app/feed/message/message.component.html
  src/app/feed/message/message.component.scss
  src/app/login/login.component.html
  src/app/login/login.component.scss
Labels: size/S
